// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int n = Integer.parseInt(args[0]);
		int i = 0;
		int lessOrEqual = 0;
		int larger = 0;
		while (i<n) {
			double random = Math.random();

			if (random<=0.5) {lessOrEqual = (lessOrEqual + 1);}
			else {larger = (larger + 1);}
			i=i+1;
					}
		double ratio = (double) larger/lessOrEqual;
		
		if (larger!=0&&lessOrEqual!=0) {
			System.out.println("> 0.5: "+larger+" times");
			System.out.println("<= 0.5: "+lessOrEqual+" times");
			System.out.println("Ratio " + ratio);}
		else {
			System.out.println("> 0.5: "+larger+" times");
			System.out.println("<= 0.5: "+lessOrEqual+" times");}


		
}
}
